name: Bug report
description: Report a reproducible problem
title: "bug: "
labels: [bug]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect to happen? What happened instead?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Repro steps
      description: Provide a minimal recipe snippet or steps to reproduce.
      render: markdown
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `snowfakery-mcp` package version (or git SHA).
    validations:
      required: false
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python version, and how you installed (pipx/PyPI/from source).
    validations:
      required: true
