name: Feature request
about: Suggest an improvement or new feature
title: ""
labels: [enhancement]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please provide a short description and how you'd use it.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line summary of the proposed feature
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this useful? What problem does it solve?
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How will we know this is done? What does success look like?
name: Feature request
description: Suggest an idea or enhancement
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: What would you like to happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Any workarounds or alternative approaches?
    validations:
      required: false
