name: Question
description: Ask a question about usage or behavior
title: "question: "
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Ask your question. Include examples/recipes if possible.
    validations:
      required: true
